### ISSUE TITLE
Doesn't actually return failure

### ISSUE THREAD

**Issue by gborcherds** [0thernet/BZGMailgunEmailValidation#4]
Cool class that I appreciated, but it passed success every time as there is not an if statement to display the failure if the is_valid key is 0.

I just added this that might help you finish this out.

``` objective-c
 if(isValid == YES) {
                                           dispatch_async(dispatch_get_main_queue(), ^{
                                               success(isValid, didYouMean);
                                           });
                                       } else {
                                           NSError *errorVal = nil;
                                           dispatch_async(dispatch_get_main_queue(), ^{
                                               failure(errorVal);
                                           });
                                       }
```

**Comment by 0thernet** [comment]
PR? :wink:

**Comment by gborcherds** [comment]
Sorry, I'm still learning how to use github and do the pull requests and everything, so I don't have one yet. Sorry.

**Comment by guytz72** [comment]
Hi, Where is this supposed to go?  I tried putting it in to replace the section 

```
                                       dispatch_async(dispatch_get_main_queue(), ^{
                                           success(isValid, didYouMean);
                                       });
```

but  still only ever got a true response.
Thanks.

**Comment by gborcherds** [comment]
I just added a pull request. I believe my code works here. https://github.com/gborcherds/BZGMailgunEmailValidation

**Comment by 0thernet** [comment]
This actually looks like a misunderstanding – sorry I didn't catch this when you opened your issue.

The API here may be a bit confusing, but `validateEmailAddress` can succeed **even if the email is valid**. Validity is passed in the success block's `isValid` argument. 

By default, `BZGMailgunEmailValidation` will also perform fallback validation using a regex, so if you're offline, basic validation will still occur. You can disable this by setting `performsFallbackValidation = NO`.
